listen: :35065
tls:
  cert: /usr/local/hysteria/server.crt
  key: /usr/local/hysteria/server.key
quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnReceiveWindow: 20971520
  maxConnReceiveWindow: 20971520
  maxIdleTimeout: 30s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false
bandwidth:
  up: 1gbps
  down: 1gbps
auth:
  type: password
  password: 0*QvM9EClL*VCZ
sniff:
  enable: true
  timeout: 2s
  rewriteDomain: false
  tcpPorts: 80,443,8000-9000
  udpPorts: all
