#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    mkdir -p /var/tmp/nginx/proxy
    mkdir -p /var/tmp/nginx/client_body
    mkdir -p /var/tmp/nginx/proxy_cache
    mkdir -p /var/tmp/nginx/uwsgi
    mkdir -p /var/tmp/nginx/proxy_cache/enginx
    mkdir -p /var/tmp/nginx/fastcgi
    mkdir -p /var/tmp/nginx/scgi
    mkdir -p /var/tmp/nginx/proxy_temp
    chown -R nginx:nginx /var/tmp/nginx
    mkdir -p /var/log/nginx
    chown -R nginx:nginx /var/log/nginx
    mkdir -p /usr/local/nginx/conf.d
    mkdir -p /home/wwwlogs || true
fi

#DEBHELPER#